name: Network and HTTP screwer.
description: Slow network to mobile levels, and add 1s delay to all messages
loglevel: 1 # Debug
proxy:
  - name: http_proxy
    config:
      host: 0.0.0.0
      port: 8181
      proxy_host: 0.0.0.0
      proxy_port: 8282
middleware:
  - name: logger
  - name: http_error
    config:
      foo: bar
      delay: 1
  - name: network_shape
    config:
      latency: 250
      target_bw: 750
      default_bw: 740 
      target_ips: 
        - 0.0.0.0
      #target_ips6: 
      target_ports: 
        - "80"
      target_protos: 
        - "tcp"
        - "udp"
        - "icmp"
